.TH vz-start 5 "October 2009" "@PRODUCT_NAME_LONG@"
.SH NAME
vz-start \- Container's startup configuration script
.SH SYNOPSIS
/etc/sysconfig/vz-scripts/vz-start
.SH DESCRIPTION
The \fBvz-start\fR script is called by \fBvzctl(8)\fR just before CT
is started. The script can be any executable file
and is usually a shell script. It can be used to perform any
additional setup of the CT such as network setup.
.P
Parameters are passed to the script in the form of environment
variables. Currently only two variables IP_ADDR and VE_ID
are defined.
.IP IP_ADDR 12
IP address(es) assigned to the CT.
.IP VE_ROOT 12
Root directory of given CT.
.IP DIST 12
Name of the distribution this CT runs (like \fBredhat-7.1\fR). Used for script
to do distribution-dependent setup.
.SH DIAGNOSTICS
The script is expected to return 0 on success, any other return code
will be printed by \fBvzctl\fR, but the CT booting will not be
terminated.
.SH SEE ALSO
.BR vzctl (8).
.SH COPYRIGHT
Copyright (C) 1999-@LAST_COPYRIGHT_YEAR@, @COPYRIGHT_OWNER@. All rights reserved.
