.\" $Id$
.TH vzcpucheck 8 "April 2012" "OpenVZ"
.SH NAME
vzcpucheck \- show information about the CPU power and utilization.
.SH SYNOPSIS
vzcpucheck [\fB-v\fR] [\fB-x\fR]
.SH DESCRIPTION
This script outputs information on the CPU power and utilization.
.SH OPTIONS
.IP \fB-v\fR
Display information for each CT.
.IP \fB-x\fR
Output in XML format.
.SH RETURN CODE
Returns 0 upon success.
.SH SEE ALSO
.BR vzctl (8).
.SH COPYRIGHT
Copyright (c) 1999-2015 Parallels IP Holdings GmbH. All rights reserved.
