.\" $Id$
.TH vzpid 8 "October 2009" "@PRODUCT_NAME_SHORT@"
.SH NAME
vzpid \- display the CT id given the process id (pid).
.SH SYNOPSIS
vzpid [\fB-h\fR] [\fIpid\fR [...]]
.SH DESCRIPTION
This script displays the CT id the process with the given \fIid\fR belongs to.
.SH OPTIONS
.IP \fIpid\fR
Enter the \fIpid\fR of the process to display the CT id where the process takes place.
.SH RETURN CODE
Returns 0 upon a successful execution.
.SH SEE ALSO
.BR vzctl (8).
.SH COPYRIGHT
Copyright (c) 1999-2015 Parallels IP Holdings GmbH. All rights reserved.

