.TH vzreboot 8 "April 2012" "@PRODUCT_NAME_SHORT@"
.SH NAME
\fBvzreboot\fR \- @PRODUCT_NAME_SHORT@ fast reboot utility.
.SH SYNOPSIS
\fBvzreboot\fR [\fIkernel_version\fR]
.SH DESCRIPTION
vzreboot is a wrapper for the kexec utility. This utility uses the default kernel from
/etc/grub.conf to directly load it into memory (skipping the hardware initialization phase)
and then boots the new kernel.
With \fIkernel_version\fR, the utility boots the specified kernel.
.TP
.SH SEE ALSO
.BR kexec (8).
.SH COPYRIGHT
Copyright (c) 2012-2017, Parallels International GmbH. All rights reserved.
Copyright (c) 2017-2019 Virtuozzo International GmbH. All rights reserved.
