#!/bin/bash
# Copyright (c) 2017, Parallels International GmbH. All rights reserved.
#

ctid=`/usr/sbin/vzlist -Ho veid,device 2>/dev/null | awk '/'"$ID"'/{print $1}'`
[ -z "$ctid" ] && exit 0

echo "`date --iso-8601=seconds` fserror : Container $ctid : fserror on $ID" >> /var/log/vzctl.log

eval $(. /etc/vz/vz.conf && echo ON_VE_FSERROR="${ON_VE_FSERROR}")

case "$ON_VE_FSERROR" in
suspend)
	/usr/sbin/vzctl suspend $ctid >/dev/null 2>&1
	;;
recover)
	/usr/sbin/vzctl suspend $ctid >/dev/null 2>&1 &&
		/usr/sbin/vzctl resume $ctid >/dev/null 2>&1
	;;
*)
	/usr/sbin/vzctl stop $ctid --fast >/dev/null 2>&1
	;;
esac	
