#!/bin/bash
# Copyright (c) 1999-2017, Parallels International GmbH. All rights reserved.
# Copyright (c) 2017-2019 Virtuozzo International GmbH. All rights reserved.
#
# This script clean CT resources on stop event
#

prvt=`/usr/sbin/vzlist -Ho private $ID 2>/dev/null`
[ -f "$prvt/.running" ] && /usr/sbin/vzctl stop $ID --force >/dev/null 2>&1
