#!/bin/bash
# Copyright (C) Parallels IP Holdings GmbH, 1999-2014. All rights reserved.
#
# This script start CT on reboot event
#
. /etc/vz/vz.conf
. /etc/vz/conf/vz-functions

VEIP=/proc/vz/veip

clear_ve_net()
{
        local ip ips

	[ -f "$VE_STATE_DIR/$ID" ] || return

	ips=$(cat "$VE_STATE_DIR/$ID" 2>/dev/null)

	[ -n "${LOGFILE}" ] || \	
		echo "`date --iso-8601=seconds` venetclean : Container $ID : clear ips: $ips" >> ${LOGFILE}

	for ip in $ips; do
		if ! grep -qw "${ip}" $VEIP 2>/dev/null; then
			vzdelrouting $ip
			vzarp del $ip
		fi
	done

	rm -f "$VE_STATE_DIR/$ID"
}

ps -o cmd -C vzctl 2>/dev/null | egrep -qw "[a-z]+ $ID" && exit 0

for ((i=0; i<10; i++)); do
	if ! vzctl --quiet status $ID | grep -wq running; then
		break
	fi
	sleep $i
done

clear_ve_net
