#!/bin/sh
#
# Copyright (C) SWsoft, 1999-2007. All rights reserved.
# All rights reserved.
#
# Simple script that prints location of VE private area
# Usage: vzgetpa VEID
# See also vzgetpa(8) man page

VEID=$1
PROGNAME=`basename $0`

function usage()
{
	echo "Usage: $PROGNAME VEID" 1>&2
	exit 0
}

test $# -eq 1 || usage

. /etc/vz/vz.conf

if test -f /etc/vz/conf/$VEID.conf; then
	. /etc/vz/conf/$VEID.conf
fi


echo $VE_PRIVATE
