#!/bin/sh
#
#  Copyright (C) 1999-2015 Parallels IP Holdings GmbH
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# Simple script that prints location of VE private area
# Usage: vzgetpa VEID
# See also vzgetpa(8) man page

VEID=$1
PROGNAME=`basename $0`

function usage()
{
	echo "Usage: $PROGNAME VEID" 1>&2
	exit 0
}

test $# -eq 1 || usage

. /etc/vz/vz.conf

if test -f /etc/vz/conf/$VEID.conf; then
	. /etc/vz/conf/$VEID.conf
fi


echo $VE_PRIVATE
