#!/bin/sh
#
#  Copyright (c) 1999-2017, Parallels International GmbH. All rights reserved.
#
#  This file is part of OpenVZ. OpenVZ is free software; you can redistribute
#  it and/or modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the License,
#  or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#  02110-1301, USA.
#
#  Our contact details: Parallels International GmbH, Vordergasse 59, 8200
#  Schaffhausen, Switzerland.
#
# Simple script that prints location of VE private area
# Usage: vzgetpa VEID
# See also vzgetpa(8) man page

VEID=$1
PROGNAME=`basename $0`

function usage()
{
	echo "Usage: $PROGNAME VEID" 1>&2
	exit 0
}

test $# -eq 1 || usage

. /etc/vz/vz.conf

if test -f /etc/vz/conf/$VEID.conf; then
	. /etc/vz/conf/$VEID.conf
fi


echo $VE_PRIVATE
