#!/bin/bash
#  Copyright (c) 1999-2017, Parallels International GmbH. All rights reserved.
# Copyright (c) 2017-2019 Virtuozzo International GmbH. All rights reserved.
#
#  This file is part of OpenVZ. OpenVZ is free software; you can redistribute
#  it and/or modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the License,
#  or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#  02110-1301, USA.
#
#  Our contact details: Virtuozzo International GmbH, Vordergasse 59, 8200
#  Schaffhausen, Switzerland.
#
# See also vzpid(8) man page


veidmark='envID:'
namemark='Name:'

function usage()
{
	echo "Usage: vzpid [pid ...] [-h]"
}

function header()
{
	echo "Pid	VEID	Name"
}

function getveid()
{
	local pid=$1

	[ -f /proc/${pid}/status ] || return
	cat /proc/${pid}/status | \
awk -v pid=${pid} 'BEGIN{veid=0} /^'${namemark}'|^'${veidmark}'/{
	if ($1 == "'${namemark}'") {
		name = $2;
	} else if ($1 == "'${veidmark}'") {
		veid = $2;
	}
}
END{
	printf("%d\t%s\t%s\n", pid, veid, name);
}'
}

pidlist=
if [ $# -eq 0 ]; then
	usage
	exit 1
elif [ $# -eq 1 -a "x$1" = "x-" ]; then
	while read pid; do
		pidlist="${pidlist} ${pid}"
	done
elif [ $# -eq 1 -a "x$1" = "x-h" ]; then
	usage
	exit 0
else
	pidlist=$*
fi
header
for i in ${pidlist}; do
	getveid ${i}
done

